const FIRSTNAME_MIN = 2;
const FIRSTNAME_MAX = 20;
const MIDDLENAME_MIN = 2;
const MIDDLENAME_MAX = 20;
const LASTNAME_MIN = 2;
const LASTNAME_MAX = 20;
const PHONENO_MIN = 10;
const PHONENO_MAX = 10;
const COMPANY_NAME_MIN = 2;
const COMPANY_NAME_MAX = 60;
const PROJECT_NAME_MIN = 2;
const PROJECT_NAME_MAX = 30;
const SUB_PROJECT_NAME_MIN = 2;
const SUB_PROJECT_NAME_MAX = 30;

module.exports = {
  FIRSTNAME_MIN,
  FIRSTNAME_MAX,
  MIDDLENAME_MIN,
  MIDDLENAME_MAX,
  LASTNAME_MIN,
  LASTNAME_MAX,
  PHONENO_MIN,
  PHONENO_MAX,
  COMPANY_NAME_MIN,
  COMPANY_NAME_MAX,
  PROJECT_NAME_MIN,
  PROJECT_NAME_MAX,
  SUB_PROJECT_NAME_MIN,
  SUB_PROJECT_NAME_MAX,
};
