const FIRSTNAME_MIN = 2;
const FIRSTNAME_MAX = 20;
const MIDDLENAME_MIN = 2;
const MIDDLENAME_MAX = 20;
const LASTNAME_MIN = 2;
const LASTNAME_MAX = 20;
const PHONENO_MIN = 10;
const PHONENO_MAX = 10;
const COMPANYNAME_MIN = 2;
const COMPANYNAME_MAX = 60;

module.exports = {
  FIRSTNAME_MIN,
  FIRSTNAME_MAX,
  MIDDLENAME_MIN,
  MIDDLENAME_MAX,
  LASTNAME_MIN,
  LASTNAME_MAX,
  PHONENO_MIN,
  PHONENO_MAX,
  COMPANYNAME_MIN,
  COMPANYNAME_MAX,
};
