const data = [
  {
    companyName: "Innojam",
    companyDescription: "Disp fx of unsp radial styloid pro, 7thM",
    companyPhoneNo: "5574107381",
    companyEmailId: "tgutierrez0@furl.net",
    createdBy: "Tiffani",
    createdDate: "4/22/2022",
    status: "active",
  },
  {
    companyName: "Flashpoint",
    companyDescription: "Disp fx of dist pole of navic bone of r wrs, 7thD",
    companyPhoneNo: "4007561826",
    companyEmailId: "agriniov1@t.co",
    createdBy: "Arabele",
    createdDate: "9/3/2021",
    status: "inactive",
  },
  {
    companyName: "Gabtype",
    companyDescription:
      "Nondisp oblique fracture of shaft of right fibula, sequela",
    companyPhoneNo: "6956624639",
    companyEmailId: "chanstock2@furl.net",
    createdBy: "Cinnamon",
    createdDate: "2/11/2022",
    status: "active",
  },
  {
    companyName: "Quimm",
    companyDescription:
      "Drown d/t thrown ovrbrd by motion of unsp wtrcrft, subs",
    companyPhoneNo: "7337022212",
    companyEmailId: "djarley3@tumblr.com",
    createdBy: "Dacia",
    createdDate: "7/16/2021",
    status: "active",
  },
  {
    companyName: "Ntag",
    companyDescription:
      "Lead-induced chronic gout, unspecified knee, without tophus",
    companyPhoneNo: "6625871552",
    companyEmailId: "cblazey4@dagondesign.com",
    createdBy: "Christos",
    createdDate: "12/3/2021",
    status: "inactive",
  },
  {
    companyName: "Voolith",
    companyDescription:
      "Exposure to ignition of oth clothing and apparel, subs",
    companyPhoneNo: "1331984843",
    companyEmailId: "morman5@com.com",
    createdBy: "Melina",
    createdDate: "2/19/2022",
    status: "active",
  },
  {
    companyName: "Tagfeed",
    companyDescription:
      "Occupant (driver) (passenger) of hv veh injured in unsp traf",
    companyPhoneNo: "5282089380",
    companyEmailId: "mesmonde6@skype.com",
    createdBy: "Mandie",
    createdDate: "10/5/2021",
    status: "inactive",
  },
  {
    companyName: "Feedmix",
    companyDescription: "Dislocation of tarsal joint of left foot, subs encntr",
    companyPhoneNo: "8786442910",
    companyEmailId: "ablakebrough7@artisteer.com",
    createdBy: "Alisa",
    createdDate: "4/7/2022",
    status: "active",
  },
  {
    companyName: "Fliptune",
    companyDescription:
      "Sltr-haris Type I physeal fx phalanx of right toe, 7thG",
    companyPhoneNo: "8698965957",
    companyEmailId: "agrishanov8@hp.com",
    createdBy: "Alfie",
    createdDate: "5/23/2022",
    status: "active",
  },
  {
    companyName: "Yakitri",
    companyDescription: "Displ seg fx shaft of ulna, r arm, 7thK",
    companyPhoneNo: "9911695549",
    companyEmailId: "mdossit9@networkadvertising.org",
    createdBy: "Marlene",
    createdDate: "3/21/2022",
    status: "active",
  },
  {
    companyName: "Thoughtsphere",
    companyDescription:
      "Nondisp unsp fx right lesser toe(s), subs for fx w malunion",
    companyPhoneNo: "8044184543",
    companyEmailId: "lmatterdacea@cyberchimps.com",
    createdBy: "Lacie",
    createdDate: "8/16/2021",
    status: "active",
  },
  {
    companyName: "Tavu",
    companyDescription: "HTLV-II as the cause of diseases classified elsewhere",
    companyPhoneNo: "3704891861",
    companyEmailId: "tcoltartb@usatoday.com",
    createdBy: "Tessie",
    createdDate: "2/20/2022",
    status: "active",
  },
  {
    companyName: "Feedfish",
    companyDescription: "Acute sinusitis, unspecified",
    companyPhoneNo: "1675778356",
    companyEmailId: "lcarreckc@github.com",
    createdBy: "Leeland",
    createdDate: "8/23/2021",
    status: "inactive",
  },
  {
    companyName: "Devcast",
    companyDescription: "Nondisp fx of dist phalanx of l mid fngr, 7thP",
    companyPhoneNo: "7302376235",
    companyEmailId: "jjarvilled@cbsnews.com",
    createdBy: "Jerrie",
    createdDate: "11/10/2021",
    status: "active",
  },
  {
    companyName: "Flashpoint",
    companyDescription: "Tuberculous female pelvic inflammatory disease",
    companyPhoneNo: "4809990644",
    companyEmailId: "jpavice@linkedin.com",
    createdBy: "Jesse",
    createdDate: "8/8/2021",
    status: "active",
  },
  {
    companyName: "Topiczoom",
    companyDescription: "Corpus luteum cyst of ovary, unspecified side",
    companyPhoneNo: "2738337811",
    companyEmailId: "otrokef@spiegel.de",
    createdBy: "Oberon",
    createdDate: "2/26/2022",
    status: "active",
  },
  {
    companyName: "Vipe",
    companyDescription:
      "Toxic effect of venom of African and Asian snake, acc, sqla",
    companyPhoneNo: "8212623025",
    companyEmailId: "lmcmilliang@bing.com",
    createdBy: "Lindi",
    createdDate: "9/6/2021",
    status: "inactive",
  },
  {
    companyName: "Trupe",
    companyDescription:
      "Subluxation of T8/T9 thoracic vertebra, initial encounter",
    companyPhoneNo: "3875384431",
    companyEmailId: "reggletonh@cdc.gov",
    createdBy: "Rowland",
    createdDate: "6/12/2022",
    status: "active",
  },
  {
    companyName: "BlogXS",
    companyDescription:
      "Lacerat unsp blood vessel at shldr/up arm, left arm, sequela",
    companyPhoneNo: "3235575256",
    companyEmailId: "gkauffmani@cocolog-nifty.com",
    createdBy: "Godwin",
    createdDate: "5/30/2022",
    status: "active",
  },
  {
    companyName: "Gigaclub",
    companyDescription:
      "Oth disp fx of sixth cervical vertebra, init for opn fx",
    companyPhoneNo: "4861242197",
    companyEmailId: "dcantillonj@wikia.com",
    createdBy: "Donetta",
    createdDate: "4/20/2022",
    status: "inactive",
  },
  {
    companyName: "Mita",
    companyDescription: "Other specified disorders of tympanic membrane",
    companyPhoneNo: "2881098624",
    companyEmailId: "hsingyardk@apple.com",
    createdBy: "Hinda",
    createdDate: "4/17/2022",
    status: "active",
  },
  {
    companyName: "Livetube",
    companyDescription: "Nondisp oblique fx shaft of r ulna, 7thC",
    companyPhoneNo: "1782387129",
    companyEmailId: "spiercel@ocn.ne.jp",
    createdBy: "Silas",
    createdDate: "9/13/2021",
    status: "inactive",
  },
  {
    companyName: "Zoomcast",
    companyDescription:
      "Burn of 3rd deg mu right fingers (nail), not inc thumb, subs",
    companyPhoneNo: "1312428939",
    companyEmailId: "dmcasparanm@ebay.com",
    createdBy: "Darwin",
    createdDate: "6/16/2022",
    status: "active",
  },
  {
    companyName: "Rooxo",
    companyDescription:
      "Corros 2nd deg mul left fingers (nail), inc thumb, init",
    companyPhoneNo: "1492983577",
    companyEmailId: "astaggn@pen.io",
    createdBy: "Adam",
    createdDate: "5/25/2022",
    status: "active",
  },
  {
    companyName: "Fivebridge",
    companyDescription: "Radiohumeral (joint) sprain of right elbow",
    companyPhoneNo: "1377913159",
    companyEmailId: "jirvingo@bigcartel.com",
    createdBy: "Jaimie",
    createdDate: "2/24/2022",
    status: "active",
  },
  {
    companyName: "Trupe",
    companyDescription:
      "Toxic effect of methanol, accidental (unintentional), subs",
    companyPhoneNo: "6283575475",
    companyEmailId: "asedmanp@imdb.com",
    createdBy: "Abel",
    createdDate: "7/9/2021",
    status: "inactive",
  },
  {
    companyName: "Zoomlounge",
    companyDescription: "Corrosion of unspecified degree of forehead and cheek",
    companyPhoneNo: "6527320033",
    companyEmailId: "crouseq@ibm.com",
    createdBy: "Catha",
    createdDate: "9/24/2021",
    status: "active",
  },
  {
    companyName: "Jatri",
    companyDescription:
      "Complete traum amp of left shldr/up arm, level unsp, sequela",
    companyPhoneNo: "6455412710",
    companyEmailId: "echapmanr@creativecommons.org",
    createdBy: "Edsel",
    createdDate: "11/27/2021",
    status: "inactive",
  },
  {
    companyName: "Jetpulse",
    companyDescription:
      "Fall into natural body of water striking water surface",
    companyPhoneNo: "2273734659",
    companyEmailId: "mthicks@mediafire.com",
    createdBy: "Morie",
    createdDate: "2/12/2022",
    status: "inactive",
  },
  {
    companyName: "Oyondu",
    companyDescription:
      "Sltr-haris Type IV physeal fx unspecified calcaneus, init",
    companyPhoneNo: "5533533797",
    companyEmailId: "blamblet@dailymotion.com",
    createdBy: "Brandi",
    createdDate: "5/4/2022",
    status: "inactive",
  },
  {
    companyName: "Kimia",
    companyDescription:
      "Oth fracture of right acetabulum, subs for fx w nonunion",
    companyPhoneNo: "5604043499",
    companyEmailId: "cshineu@utexas.edu",
    createdBy: "Cory",
    createdDate: "1/23/2022",
    status: "inactive",
  },
  {
    companyName: "Rhyloo",
    companyDescription:
      "Oth chronic resp diseases origin in the perinatal period",
    companyPhoneNo: "3303806914",
    companyEmailId: "awaitev@google.com.hk",
    createdBy: "Amitie",
    createdDate: "9/7/2021",
    status: "active",
  },
  {
    companyName: "Jetwire",
    companyDescription:
      "Multiple defects of retina without detachment, unsp eye",
    companyPhoneNo: "5436802471",
    companyEmailId: "cdevitaw@rakuten.co.jp",
    createdBy: "Cortie",
    createdDate: "3/29/2022",
    status: "inactive",
  },
  {
    companyName: "Browsebug",
    companyDescription: "Nondisp pilon fx l tibia, 7thJ",
    companyPhoneNo: "2373525331",
    companyEmailId: "lvanichkovx@quantcast.com",
    createdBy: "Lammond",
    createdDate: "5/16/2022",
    status: "inactive",
  },
  {
    companyName: "Mycat",
    companyDescription:
      "Hyperparathyroidism and other disorders of parathyroid gland",
    companyPhoneNo: "4727323017",
    companyEmailId: "tbeaudryy@domainmarket.com",
    createdBy: "Trev",
    createdDate: "8/21/2021",
    status: "inactive",
  },
  {
    companyName: "Jabberbean",
    companyDescription: "Corrosion of left eye and adnexa, part unspecified",
    companyPhoneNo: "7791771937",
    companyEmailId: "ccarayolz@hostgator.com",
    createdBy: "Chrissy",
    createdDate: "5/7/2022",
    status: "inactive",
  },
  {
    companyName: "Livefish",
    companyDescription: "Corrosion of third degree of left lower leg, sequela",
    companyPhoneNo: "2719191504",
    companyEmailId: "vtook10@boston.com",
    createdBy: "Virgilio",
    createdDate: "7/21/2021",
    status: "active",
  },
  {
    companyName: "Demimbu",
    companyDescription:
      "Nontraumatic intcrbl hemorrhage in hemisphere, subcortical",
    companyPhoneNo: "1525684905",
    companyEmailId: "rpopplestone11@mail.ru",
    createdBy: "Richmound",
    createdDate: "4/25/2022",
    status: "inactive",
  },
  {
    companyName: "Blognation",
    companyDescription:
      "Salter-Harris Type I physeal fracture of left metatarsal",
    companyPhoneNo: "8082289530",
    companyEmailId: "bpuller12@feedburner.com",
    createdBy: "Buddy",
    createdDate: "9/14/2021",
    status: "active",
  },
  {
    companyName: "Zoovu",
    companyDescription:
      "Lacerat extn musc/fasc/tend r idx fngr at wrs/hnd lv, init",
    companyPhoneNo: "6307520368",
    companyEmailId: "dhaysman13@yelp.com",
    createdBy: "Donny",
    createdDate: "11/5/2021",
    status: "inactive",
  },
  {
    companyName: "Voonyx",
    companyDescription: "Laceration of fallopian tube, bilateral, subs encntr",
    companyPhoneNo: "7862436703",
    companyEmailId: "kswindon14@sina.com.cn",
    createdBy: "Kali",
    createdDate: "10/9/2021",
    status: "inactive",
  },
  {
    companyName: "Twitterbridge",
    companyDescription: "Unsp fx upr end unsp rad, 7thE",
    companyPhoneNo: "9079152939",
    companyEmailId: "bpeartree15@indiatimes.com",
    createdBy: "Belicia",
    createdDate: "9/4/2021",
    status: "active",
  },
  {
    companyName: "Fliptune",
    companyDescription:
      "Unsp fx lower end unsp ulna, subs for clos fx w routn heal",
    companyPhoneNo: "6576156905",
    companyEmailId: "nwinson16@google.com",
    createdBy: "Nicolais",
    createdDate: "8/9/2021",
    status: "inactive",
  },
  {
    companyName: "Yamia",
    companyDescription: "Recurrent erosion of cornea, bilateral",
    companyPhoneNo: "9765813739",
    companyEmailId: "rboulger17@g.co",
    createdBy: "Reggie",
    createdDate: "1/29/2022",
    status: "inactive",
  },
  {
    companyName: "Kanoodle",
    companyDescription: "Toxic effect of fusel oil, undetermined, subs encntr",
    companyPhoneNo: "7588112576",
    companyEmailId: "djamrowicz18@cisco.com",
    createdBy: "Dorri",
    createdDate: "3/20/2022",
    status: "inactive",
  },
  {
    companyName: "Oyoloo",
    companyDescription: "Unsp nondisp fx of second cervical vertebra, init",
    companyPhoneNo: "9566674023",
    companyEmailId: "jvigus19@accuweather.com",
    createdBy: "Joyous",
    createdDate: "10/5/2021",
    status: "inactive",
  },
  {
    companyName: "Reallinks",
    companyDescription:
      "Open bite of left middle finger w/o damage to nail, subs",
    companyPhoneNo: "6635628506",
    companyEmailId: "dstealfox1a@tumblr.com",
    createdBy: "Doralin",
    createdDate: "9/12/2021",
    status: "inactive",
  },
  {
    companyName: "Thoughtmix",
    companyDescription:
      "Laceration w foreign body of finger w damage to nail, subs",
    companyPhoneNo: "7896355898",
    companyEmailId: "jdoberer1b@dropbox.com",
    createdBy: "Jobi",
    createdDate: "4/15/2022",
    status: "inactive",
  },
  {
    companyName: "Quatz",
    companyDescription: "Antisocial behavior",
    companyPhoneNo: "6754137048",
    companyEmailId: "sstitt1c@zimbio.com",
    createdBy: "Stepha",
    createdDate: "4/22/2022",
    status: "inactive",
  },
  {
    companyName: "Livepath",
    companyDescription:
      "Path fracture, right finger(s), subs for fx w routn heal",
    companyPhoneNo: "5037174357",
    companyEmailId: "aduddell1d@free.fr",
    createdBy: "Ailis",
    createdDate: "5/5/2022",
    status: "inactive",
  },
  {
    companyName: "Brainsphere",
    companyDescription: "Traum subdr hem w LOC of unsp duration, init",
    companyPhoneNo: "9026210601",
    companyEmailId: "hpretor1e@nsw.gov.au",
    createdBy: "Heriberto",
    createdDate: "1/13/2022",
    status: "active",
  },
  {
    companyName: "Ailane",
    companyDescription: "Unsp fracture of right talus, init for clos fx",
    companyPhoneNo: "8747253057",
    companyEmailId: "scrownshaw1f@mlb.com",
    createdBy: "Sholom",
    createdDate: "5/26/2022",
    status: "active",
  },
  {
    companyName: "Jatri",
    companyDescription: "Anterior corneal pigmentations, unspecified eye",
    companyPhoneNo: "4836057896",
    companyEmailId: "rpate1g@spiegel.de",
    createdBy: "Romeo",
    createdDate: "10/27/2021",
    status: "inactive",
  },
  {
    companyName: "Eabox",
    companyDescription:
      "Toxic effect of insecticides, intentional self-harm, subs",
    companyPhoneNo: "4876347924",
    companyEmailId: "ajillitt1h@behance.net",
    createdBy: "Ann",
    createdDate: "4/27/2022",
    status: "inactive",
  },
  {
    companyName: "Dabjam",
    companyDescription:
      "Ankylosing hyperostosis, occipito-atlanto-axial region",
    companyPhoneNo: "3519207713",
    companyEmailId: "schesher1i@blogtalkradio.com",
    createdBy: "Sarge",
    createdDate: "4/18/2022",
    status: "inactive",
  },
  {
    companyName: "Blogspan",
    companyDescription:
      "Triplet preg w two or more monoamnio fetuses, third tri",
    companyPhoneNo: "5411187791",
    companyEmailId: "thenriksson1j@multiply.com",
    createdBy: "Titus",
    createdDate: "11/24/2021",
    status: "inactive",
  },
  {
    companyName: "Buzzdog",
    companyDescription: "Plasmodium malariae malaria with nephropathy",
    companyPhoneNo: "9854250646",
    companyEmailId: "mpetren1k@wp.com",
    createdBy: "Marchelle",
    createdDate: "7/11/2021",
    status: "inactive",
  },
  {
    companyName: "Brainverse",
    companyDescription:
      "Rider of nonpowr wtrcrft struck by powered watercraft, init",
    companyPhoneNo: "9498133742",
    companyEmailId: "kcanfer1l@deliciousdays.com",
    createdBy: "Kristyn",
    createdDate: "2/9/2022",
    status: "inactive",
  },
  {
    companyName: "Avamba",
    companyDescription: "Adverse effect of opium, sequela",
    companyPhoneNo: "8735674772",
    companyEmailId: "hpeniman1m@cdbaby.com",
    createdBy: "Hoebart",
    createdDate: "8/20/2021",
    status: "inactive",
  },
  {
    companyName: "Dabfeed",
    companyDescription: "Infected hydrocele",
    companyPhoneNo: "9888723483",
    companyEmailId: "dvollam1n@istockphoto.com",
    createdBy: "Dorene",
    createdDate: "2/27/2022",
    status: "active",
  },
  {
    companyName: "Youspan",
    companyDescription:
      "Disp fx of trapezoid, left wrist, subs for fx w delay heal",
    companyPhoneNo: "2057716242",
    companyEmailId: "alaundon1o@mtv.com",
    createdBy: "Alayne",
    createdDate: "11/12/2021",
    status: "inactive",
  },
  {
    companyName: "Dabtype",
    companyDescription: "Child sexual abuse, confirmed, subsequent encounter",
    companyPhoneNo: "6497375527",
    companyEmailId: "sgreenaway1p@themeforest.net",
    createdBy: "Sasha",
    createdDate: "7/13/2021",
    status: "active",
  },
  {
    companyName: "Katz",
    companyDescription: "Posterior dislocation of unspecified humerus",
    companyPhoneNo: "2976214284",
    companyEmailId: "aocanavan1q@4shared.com",
    createdBy: "Aime",
    createdDate: "4/11/2022",
    status: "active",
  },
  {
    companyName: "Talane",
    companyDescription: "Jump/div into unsp water causing oth injury, sequela",
    companyPhoneNo: "2553212385",
    companyEmailId: "hletts1r@printfriendly.com",
    createdBy: "Hussein",
    createdDate: "1/3/2022",
    status: "active",
  },
  {
    companyName: "Yozio",
    companyDescription: "Intestinal myiasis",
    companyPhoneNo: "7367826724",
    companyEmailId: "bmcilreavy1s@simplemachines.org",
    createdBy: "Bentley",
    createdDate: "11/8/2021",
    status: "active",
  },
  {
    companyName: "Katz",
    companyDescription:
      "Unsp comp of fb acc left in body fol injection or immuniz",
    companyPhoneNo: "2023310590",
    companyEmailId: "tapplegarth1t@guardian.co.uk",
    createdBy: "Tybie",
    createdDate: "6/25/2022",
    status: "active",
  },
  {
    companyName: "Oyoba",
    companyDescription: "Rupture of synovium, elbow",
    companyPhoneNo: "5469896860",
    companyEmailId: "astidever1u@columbia.edu",
    createdBy: "Alasteir",
    createdDate: "1/28/2022",
    status: "inactive",
  },
  {
    companyName: "Gigashots",
    companyDescription: "Corrosion of first degree of forearm",
    companyPhoneNo: "4198052944",
    companyEmailId: "lsaltmarshe1v@buzzfeed.com",
    createdBy: "Lucinda",
    createdDate: "10/1/2021",
    status: "inactive",
  },
  {
    companyName: "Zoombeat",
    companyDescription:
      "Age-rel osteopor w current path fracture, unsp femur, init",
    companyPhoneNo: "2081636352",
    companyEmailId: "smanus1w@bizjournals.com",
    createdBy: "Suki",
    createdDate: "5/5/2022",
    status: "active",
  },
  {
    companyName: "Trudeo",
    companyDescription:
      "Unspecified superficial injury of eyelid and periocular area",
    companyPhoneNo: "3208528953",
    companyEmailId: "etretwell1x@phpbb.com",
    createdBy: "Elsi",
    createdDate: "11/11/2021",
    status: "active",
  },
  {
    companyName: "Zoomzone",
    companyDescription: "Nondisp fx of lateral malleolus of unsp fibula, 7thE",
    companyPhoneNo: "3523513179",
    companyEmailId: "oposnett1y@linkedin.com",
    createdBy: "Ogdon",
    createdDate: "6/8/2022",
    status: "inactive",
  },
  {
    companyName: "Tagopia",
    companyDescription:
      "Pedl cyc driver injured in clsn w rail trn/veh in traf, subs",
    companyPhoneNo: "3464631511",
    companyEmailId: "cbaroche1z@ycombinator.com",
    createdBy: "Costanza",
    createdDate: "12/31/2021",
    status: "active",
  },
  {
    companyName: "Gabvine",
    companyDescription:
      "Oth injury of anterior tibial artery, left leg, subs encntr",
    companyPhoneNo: "7971819314",
    companyEmailId: "gmalyon20@dyndns.org",
    createdBy: "Geraldine",
    createdDate: "10/31/2021",
    status: "inactive",
  },
  {
    companyName: "Plajo",
    companyDescription:
      "Burn first deg of unsp site left lower limb, ex ank/ft, init",
    companyPhoneNo: "3414875176",
    companyEmailId: "gpointer21@4shared.com",
    createdBy: "Gipsy",
    createdDate: "10/15/2021",
    status: "active",
  },
  {
    companyName: "Skaboo",
    companyDescription: "Insect bite (nonvenomous), left knee",
    companyPhoneNo: "5333645584",
    companyEmailId: "jledley22@sciencedirect.com",
    createdBy: "Jeannine",
    createdDate: "8/26/2021",
    status: "inactive",
  },
  {
    companyName: "Tazzy",
    companyDescription: "Contusion of ovary, bilateral, initial encounter",
    companyPhoneNo: "5296575819",
    companyEmailId: "mmcniven23@about.com",
    createdBy: "Moshe",
    createdDate: "1/25/2022",
    status: "inactive",
  },
  {
    companyName: "Brainlounge",
    companyDescription:
      "Laceration of adductor musc/fasc/tend unsp thigh, subs",
    companyPhoneNo: "4421661103",
    companyEmailId: "ghauxwell24@army.mil",
    createdBy: "Glenna",
    createdDate: "12/21/2021",
    status: "active",
  },
  {
    companyName: "Tagpad",
    companyDescription:
      "Primary blast injury of fallopian tube, unilateral, subs",
    companyPhoneNo: "6176071344",
    companyEmailId: "pmanby25@ted.com",
    createdBy: "Phebe",
    createdDate: "9/6/2021",
    status: "active",
  },
  {
    companyName: "Gabcube",
    companyDescription: "Disseminated superficial actinic porokeratosis (DSAP)",
    companyPhoneNo: "6598396826",
    companyEmailId: "bwringe26@nationalgeographic.com",
    createdBy: "Bria",
    createdDate: "9/15/2021",
    status: "active",
  },
  {
    companyName: "Bluezoom",
    companyDescription:
      "Posterior disp fx of sternal end of left clavicle, sequela",
    companyPhoneNo: "1028927647",
    companyEmailId: "mklauber27@wufoo.com",
    createdBy: "Major",
    createdDate: "2/22/2022",
    status: "active",
  },
  {
    companyName: "DabZ",
    companyDescription:
      "Paralytic calcification and ossification of muscle, ank/ft",
    companyPhoneNo: "2355250144",
    companyEmailId: "noiller28@acquirethisname.com",
    createdBy: "Niels",
    createdDate: "10/7/2021",
    status: "active",
  },
  {
    companyName: "Zoonder",
    companyDescription:
      "Poisn by oth antacids & anti-gstrc-sec drugs, slf-hrm, init",
    companyPhoneNo: "3233366955",
    companyEmailId: "ihugueville29@bizjournals.com",
    createdBy: "Ivett",
    createdDate: "3/16/2022",
    status: "inactive",
  },
  {
    companyName: "Agivu",
    companyDescription:
      "Burns of 80-89% of body surface w 10-19% third degree burns",
    companyPhoneNo: "7445701740",
    companyEmailId: "mattenborrow2a@wunderground.com",
    createdBy: "Malory",
    createdDate: "2/23/2022",
    status: "inactive",
  },
  {
    companyName: "Eabox",
    companyDescription: "Internuclear ophthalmoplegia, bilateral",
    companyPhoneNo: "7923063761",
    companyEmailId: "mvannuchi2b@jigsy.com",
    createdBy: "Mendel",
    createdDate: "9/18/2021",
    status: "active",
  },
  {
    companyName: "Flashdog",
    companyDescription: "Other inflammatory disorders of penis",
    companyPhoneNo: "5109188374",
    companyEmailId: "rjenkinson2c@mlb.com",
    createdBy: "Rockey",
    createdDate: "5/14/2022",
    status: "inactive",
  },
  {
    companyName: "Topdrive",
    companyDescription: "Postmeningococcal arthritis",
    companyPhoneNo: "3972217138",
    companyEmailId: "cdimeloe2d@mysql.com",
    createdBy: "Codie",
    createdDate: "11/25/2021",
    status: "active",
  },
  {
    companyName: "Mydeo",
    companyDescription: "Monocular exotropia with V pattern",
    companyPhoneNo: "2866494425",
    companyEmailId: "ljorcke2e@wunderground.com",
    createdBy: "Lynea",
    createdDate: "3/24/2022",
    status: "active",
  },
  {
    companyName: "Quimm",
    companyDescription: "Disp fx of med malleolus of l tibia, 7thN",
    companyPhoneNo: "8204112222",
    companyEmailId: "lbernardini2f@myspace.com",
    createdBy: "Louella",
    createdDate: "2/14/2022",
    status: "active",
  },
  {
    companyName: "Geba",
    companyDescription: "Nondisp commnt fx shaft of rad, unsp arm, 7thN",
    companyPhoneNo: "1615860651",
    companyEmailId: "bleighfield2g@over-blog.com",
    createdBy: "Bernadette",
    createdDate: "6/25/2022",
    status: "active",
  },
  {
    companyName: "Eazzy",
    companyDescription:
      "Disloc of prox interphaln joint of r little finger, sequela",
    companyPhoneNo: "7609031443",
    companyEmailId: "ekalinke2h@hostgator.com",
    createdBy: "Emmy",
    createdDate: "12/7/2021",
    status: "inactive",
  },
  {
    companyName: "Feedbug",
    companyDescription: "Displ seg fx shaft of r fibula, 7thE",
    companyPhoneNo: "5081460472",
    companyEmailId: "ecallis2i@lulu.com",
    createdBy: "Elwin",
    createdDate: "3/14/2022",
    status: "inactive",
  },
  {
    companyName: "Skaboo",
    companyDescription: "Unsp disp fx of surgical neck of unsp humerus, init",
    companyPhoneNo: "3262360196",
    companyEmailId: "bkynder2j@constantcontact.com",
    createdBy: "Brynna",
    createdDate: "9/10/2021",
    status: "inactive",
  },
  {
    companyName: "Digitube",
    companyDescription:
      "Nondisp oblique fracture of shaft of left radius, sequela",
    companyPhoneNo: "8211320916",
    companyEmailId: "vyakebowitch2k@soundcloud.com",
    createdBy: "Valentina",
    createdDate: "8/5/2021",
    status: "active",
  },
  {
    companyName: "Meejo",
    companyDescription:
      "Pnctr w/o fb of right eyelid and periocular area, subs",
    companyPhoneNo: "4858337740",
    companyEmailId: "ppomphrey2l@pbs.org",
    createdBy: "Peria",
    createdDate: "12/8/2021",
    status: "active",
  },
  {
    companyName: "Riffpedia",
    companyDescription:
      "Poisoning by calcium-channel blockers, undetermined, subs",
    companyPhoneNo: "5951310233",
    companyEmailId: "ajanning2m@weibo.com",
    createdBy: "Alysia",
    createdDate: "2/28/2022",
    status: "active",
  },
  {
    companyName: "Kwideo",
    companyDescription:
      "Labor and delivery complicated by prolapse of cord, fetus 2",
    companyPhoneNo: "7702756411",
    companyEmailId: "nplayford2n@mediafire.com",
    createdBy: "Nicolle",
    createdDate: "10/17/2021",
    status: "active",
  },
  {
    companyName: "Flashspan",
    companyDescription:
      "Burn of third degree of right wrist, subsequent encounter",
    companyPhoneNo: "5973398926",
    companyEmailId: "abischof2o@ustream.tv",
    createdBy: "Alene",
    createdDate: "4/17/2022",
    status: "active",
  },
  {
    companyName: "Realmix",
    companyDescription:
      "Disp fx of prox phalanx of finger, subs for fx w nonunion",
    companyPhoneNo: "2744482259",
    companyEmailId: "htavener2p@icio.us",
    createdBy: "Herminia",
    createdDate: "2/9/2022",
    status: "active",
  },
  {
    companyName: "Muxo",
    companyDescription: "Unspecified fracture of lower end of humerus",
    companyPhoneNo: "3314908829",
    companyEmailId: "eeasthope2q@zdnet.com",
    createdBy: "Emmye",
    createdDate: "11/3/2021",
    status: "inactive",
  },
  {
    companyName: "Twitterworks",
    companyDescription: "Osteitis condensans, multiple sites",
    companyPhoneNo: "1795102088",
    companyEmailId: "frevett2r@paypal.com",
    createdBy: "Fair",
    createdDate: "6/18/2022",
    status: "active",
  },
];

const db = require("../server/config/database");
let obj;
for (obj of data) {
  const keys = Object.keys(obj);
  const values = Object.values(obj);
  const sql = `insert into company (${keys}) values (${values.map(
    (item) => `'${item}'`
  )})`;
  db.query(sql);
}
