const Data = [
  {
    firstname: "Melania",
    middlename: "Dorri",
    lastname: "Allnatt",
    gender: "Female",
    dob: "11/23/1998",
    emailid: "tallnatt0@addtoany.com",
    phoneno: "6017223889",
    address: "32 Norway Maple Junction",
    tokenid: 74,
    companyid: 26,
    createdby: "Tera",
    createddate: "2/9/2021",
  },
  {
    firstname: "Ebeneser",
    middlename: "Kort",
    lastname: "Grigoletti",
    gender: "Male",
    dob: "10/17/1998",
    emailid: "jgrigoletti1@blogger.com",
    phoneno: "3889944889",
    address: "74753 Lien Drive",
    tokenid: 25,
    companyid: 96,
    createdby: "Jethro",
    createddate: "3/25/2021",
  },
  {
    firstname: "Stillmann",
    middlename: "Talbot",
    lastname: "Manssuer",
    gender: "Male",
    dob: "6/14/1998",
    emailid: "vmanssuer2@webeden.co.uk",
    phoneno: "4995209907",
    address: "480 Maryland Hill",
    tokenid: 91,
    companyid: 46,
    createdby: "Vaughan",
    createddate: "2/1/2022",
  },
  {
    firstname: "Udale",
    middlename: "Leo",
    lastname: "Penritt",
    gender: "Male",
    dob: "10/23/1998",
    emailid: "rpenritt3@miibeian.gov.cn",
    phoneno: "5786699878",
    address: "696 Ryan Street",
    tokenid: 70,
    companyid: 15,
    createdby: "Randie",
    createddate: "12/26/2021",
  },
  {
    firstname: "Edeline",
    middlename: "Cecile",
    lastname: "Windle",
    gender: "Female",
    dob: "6/15/2001",
    emailid: "awindle4@soup.io",
    phoneno: "1412726570",
    address: "56 Northfield Road",
    tokenid: 35,
    companyid: 12,
    createdby: "Almeta",
    createddate: "5/21/2021",
  },
  {
    firstname: "Ram",
    middlename: "Flint",
    lastname: "Walewicz",
    gender: "Male",
    dob: "12/13/1998",
    emailid: "cwalewicz5@de.vu",
    phoneno: "5686987815",
    address: "08 Meadow Vale Street",
    tokenid: 68,
    companyid: 74,
    createdby: "Cyrus",
    createddate: "8/9/2021",
  },
  {
    firstname: "Gayelord",
    middlename: "Mylo",
    lastname: "Thomesson",
    gender: "Male",
    dob: "5/27/1999",
    emailid: "hthomesson6@google.nl",
    phoneno: "6947839414",
    address: "2 Morningstar Way",
    tokenid: 95,
    companyid: 21,
    createdby: "Hinze",
    createddate: "1/20/2022",
  },
  {
    firstname: "Clevie",
    middlename: "Case",
    lastname: "Cuthbert",
    gender: "Male",
    dob: "4/21/2000",
    emailid: "dcuthbert7@is.gd",
    phoneno: "6414278569",
    address: "728 Duke Point",
    tokenid: 73,
    companyid: 19,
    createdby: "Dwayne",
    createddate: "9/3/2021",
  },
  {
    firstname: "Chariot",
    middlename: "Delbert",
    lastname: "Salvin",
    gender: "Male",
    dob: "10/2/1999",
    emailid: "bsalvin8@weibo.com",
    phoneno: "7704581396",
    address: "8 Westridge Crossing",
    tokenid: 74,
    companyid: 57,
    createdby: "Britt",
    createddate: "4/9/2021",
  },
  {
    firstname: "Oliver",
    middlename: "Stanislaw",
    lastname: "Skullet",
    gender: "Male",
    dob: "5/11/1999",
    emailid: "pskullet9@digg.com",
    phoneno: "2824566893",
    address: "53 Summerview Parkway",
    tokenid: 78,
    companyid: 67,
    createdby: "Park",
    createddate: "4/21/2022",
  },
  {
    firstname: "Miguelita",
    middlename: "Elberta",
    lastname: "Chessell",
    gender: "Female",
    dob: "8/19/1997",
    emailid: "echessella@washington.edu",
    phoneno: "8008067893",
    address: "397 Kropf Avenue",
    tokenid: 55,
    companyid: 99,
    createdby: "Eartha",
    createddate: "1/7/2022",
  },
  {
    firstname: "Wyndham",
    middlename: "Hussein",
    lastname: "Robb",
    gender: "Male",
    dob: "7/11/1999",
    emailid: "srobbb@youtu.be",
    phoneno: "7656486235",
    address: "9501 Sachs Court",
    tokenid: 76,
    companyid: 4,
    createdby: "Siward",
    createddate: "5/17/2021",
  },
  {
    firstname: "Saleem",
    middlename: "Forbes",
    lastname: "Dillingston",
    gender: "Male",
    dob: "1/27/2000",
    emailid: "wdillingstonc@youtube.com",
    phoneno: "5967675196",
    address: "57044 Longview Hill",
    tokenid: 69,
    companyid: 73,
    createdby: "Welbie",
    createddate: "7/31/2021",
  },
  {
    firstname: "Dennie",
    middlename: "Suzie",
    lastname: "Milbank",
    gender: "Female",
    dob: "2/14/1999",
    emailid: "mmilbankd@cloudflare.com",
    phoneno: "6775111784",
    address: "986 Pierstorff Way",
    tokenid: 29,
    companyid: 10,
    createdby: "Margy",
    createddate: "10/14/2020",
  },
  {
    firstname: "Jarad",
    middlename: "Gun",
    lastname: "Seivwright",
    gender: "Male",
    dob: "1/31/1999",
    emailid: "sseivwrighte@un.org",
    phoneno: "9921677241",
    address: "9473 Farragut Terrace",
    tokenid: 68,
    companyid: 60,
    createdby: "Stanwood",
    createddate: "4/18/2021",
  },
  {
    firstname: "Vernon",
    middlename: "Reginald",
    lastname: "Hastie",
    gender: "Male",
    dob: "10/13/1997",
    emailid: "whastief@unc.edu",
    phoneno: "9984424695",
    address: "19 Dunning Plaza",
    tokenid: 33,
    companyid: 67,
    createdby: "Wilfred",
    createddate: "8/7/2021",
  },
  {
    firstname: "Perren",
    middlename: "Shaun",
    lastname: "Fears",
    gender: "Male",
    dob: "5/23/2000",
    emailid: "gfearsg@ocn.ne.jp",
    phoneno: "5905229835",
    address: "66730 Golf Course Circle",
    tokenid: 15,
    companyid: 69,
    createdby: "Gallard",
    createddate: "3/12/2021",
  },
  {
    firstname: "Mehetabel",
    middlename: "Ann-marie",
    lastname: "Creagh",
    gender: "Female",
    dob: "11/27/2000",
    emailid: "gcreaghh@japanpost.jp",
    phoneno: "8826314065",
    address: "9595 Waxwing Circle",
    tokenid: 71,
    companyid: 88,
    createdby: "Gabriell",
    createddate: "11/29/2021",
  },
  {
    firstname: "Alvira",
    middlename: "Harriett",
    lastname: "Stapells",
    gender: "Female",
    dob: "3/27/2000",
    emailid: "cstapellsi@theatlantic.com",
    phoneno: "1679433477",
    address: "485 Prairieview Crossing",
    tokenid: 58,
    companyid: 88,
    createdby: "Cilka",
    createddate: "10/17/2020",
  },
  {
    firstname: "Ned",
    middlename: "Guillermo",
    lastname: "Petschel",
    gender: "Male",
    dob: "7/27/2000",
    emailid: "npetschelj@statcounter.com",
    phoneno: "1373670815",
    address: "1 Northport Lane",
    tokenid: 75,
    companyid: 90,
    createdby: "Nicolais",
    createddate: "7/21/2020",
  },
  {
    firstname: "Odetta",
    middlename: "Eugine",
    lastname: "Somerled",
    gender: "Female",
    dob: "10/30/1997",
    emailid: "fsomerledk@unicef.org",
    phoneno: "9639294078",
    address: "2 Village Junction",
    tokenid: 12,
    companyid: 74,
    createdby: "Fayre",
    createddate: "2/16/2021",
  },
  {
    firstname: "Chrysler",
    middlename: "Brittaney",
    lastname: "Fullylove",
    gender: "Female",
    dob: "3/22/1998",
    emailid: "rfullylovel@soup.io",
    phoneno: "4096760866",
    address: "7 Brentwood Street",
    tokenid: 2,
    companyid: 86,
    createdby: "Rochell",
    createddate: "6/18/2022",
  },
  {
    firstname: "Ariella",
    middlename: "Giralda",
    lastname: "Hovenden",
    gender: "Female",
    dob: "1/29/1999",
    emailid: "shovendenm@myspace.com",
    phoneno: "8937124155",
    address: "22385 7th Crossing",
    tokenid: 50,
    companyid: 28,
    createdby: "Stephana",
    createddate: "2/22/2022",
  },
  {
    firstname: "Inness",
    middlename: "Hillel",
    lastname: "Pasquale",
    gender: "Male",
    dob: "4/2/2001",
    emailid: "cpasqualen@japanpost.jp",
    phoneno: "9852607715",
    address: "2621 Arapahoe Way",
    tokenid: 79,
    companyid: 14,
    createdby: "Chan",
    createddate: "8/26/2021",
  },
  {
    firstname: "Margo",
    middlename: "Lissy",
    lastname: "Rainton",
    gender: "Female",
    dob: "6/25/2000",
    emailid: "lraintono@prnewswire.com",
    phoneno: "7164858827",
    address: "239 Delaware Center",
    tokenid: 53,
    companyid: 10,
    createdby: "Leticia",
    createddate: "11/5/2020",
  },
  {
    firstname: "Peder",
    middlename: "Tyson",
    lastname: "Haggish",
    gender: "Male",
    dob: "8/31/1999",
    emailid: "rhaggishp@buzzfeed.com",
    phoneno: "3845443722",
    address: "82 Hudson Point",
    tokenid: 24,
    companyid: 99,
    createdby: "Rudd",
    createddate: "8/1/2021",
  },
  {
    firstname: "Ethyl",
    middlename: "Mellie",
    lastname: "Sorsby",
    gender: "Female",
    dob: "2/3/2000",
    emailid: "tsorsbyq@github.com",
    phoneno: "7344031046",
    address: "233 Donald Trail",
    tokenid: 59,
    companyid: 66,
    createdby: "Toinette",
    createddate: "3/7/2021",
  },
  {
    firstname: "Sherlock",
    middlename: "Urson",
    lastname: "Wilber",
    gender: "Male",
    dob: "9/27/1997",
    emailid: "lwilberr@4shared.com",
    phoneno: "8579579843",
    address: "1241 Nova Pass",
    tokenid: 19,
    companyid: 95,
    createdby: "Lyman",
    createddate: "11/18/2021",
  },
  {
    firstname: "Jakie",
    middlename: "Claudian",
    lastname: "Dutchburn",
    gender: "Male",
    dob: "12/25/1998",
    emailid: "edutchburns@howstuffworks.com",
    phoneno: "8979742711",
    address: "3685 Annamark Place",
    tokenid: 23,
    companyid: 8,
    createdby: "Ernest",
    createddate: "8/8/2021",
  },
  {
    firstname: "Rosaline",
    middlename: "Jeanna",
    lastname: "Gasking",
    gender: "Female",
    dob: "11/3/1999",
    emailid: "vgaskingt@51.la",
    phoneno: "5171472969",
    address: "42940 Carioca Crossing",
    tokenid: 86,
    companyid: 14,
    createdby: "Vinny",
    createddate: "6/21/2022",
  },
  {
    firstname: "Else",
    middlename: "Abbe",
    lastname: "Dumingos",
    gender: "Female",
    dob: "7/16/1997",
    emailid: "adumingosu@altervista.org",
    phoneno: "3826058695",
    address: "628 Orin Junction",
    tokenid: 31,
    companyid: 21,
    createdby: "Aubree",
    createddate: "9/20/2020",
  },
  {
    firstname: "Guinevere",
    middlename: "Ninnette",
    lastname: "Jeratt",
    gender: "Female",
    dob: "9/26/1998",
    emailid: "ljerattv@home.pl",
    phoneno: "6966583611",
    address: "4644 West Alley",
    tokenid: 96,
    companyid: 17,
    createdby: "Lorry",
    createddate: "1/11/2021",
  },
  {
    firstname: "Abbe",
    middlename: "Brodie",
    lastname: "Lindeboom",
    gender: "Male",
    dob: "10/14/1998",
    emailid: "hlindeboomw@amazon.com",
    phoneno: "7246097667",
    address: "94 Cambridge Parkway",
    tokenid: 41,
    companyid: 58,
    createdby: "Humbert",
    createddate: "1/6/2022",
  },
  {
    firstname: "Timmi",
    middlename: "Mil",
    lastname: "Tunniclisse",
    gender: "Female",
    dob: "2/25/2000",
    emailid: "etunniclissex@jugem.jp",
    phoneno: "6248505268",
    address: "5461 Swallow Court",
    tokenid: 35,
    companyid: 6,
    createdby: "Elsey",
    createddate: "12/21/2020",
  },
  {
    firstname: "Chlo",
    middlename: "Stefa",
    lastname: "Sutherington",
    gender: "Female",
    dob: "10/2/1997",
    emailid: "rsutheringtony@a8.net",
    phoneno: "8195677223",
    address: "81170 Corscot Terrace",
    tokenid: 55,
    companyid: 53,
    createdby: "Rona",
    createddate: "8/24/2021",
  },
  {
    firstname: "Gertrude",
    middlename: "Jyoti",
    lastname: "Bullough",
    gender: "Female",
    dob: "2/7/2000",
    emailid: "lbulloughz@360.cn",
    phoneno: "2481578156",
    address: "02465 Rockefeller Lane",
    tokenid: 65,
    companyid: 71,
    createdby: "Lindi",
    createddate: "12/30/2021",
  },
  {
    firstname: "Garrek",
    middlename: "Hermy",
    lastname: "Samson",
    gender: "Male",
    dob: "9/28/1997",
    emailid: "asamson10@google.ca",
    phoneno: "7995410791",
    address: "3 Kinsman Alley",
    tokenid: 13,
    companyid: 19,
    createdby: "Arron",
    createddate: "6/9/2022",
  },
  {
    firstname: "Orran",
    middlename: "Natal",
    lastname: "Hovie",
    gender: "Male",
    dob: "3/2/1998",
    emailid: "lhovie11@fema.gov",
    phoneno: "3219919419",
    address: "3481 Shasta Park",
    tokenid: 71,
    companyid: 54,
    createdby: "Leroy",
    createddate: "10/7/2020",
  },
  {
    firstname: "Terry",
    middlename: "Hewe",
    lastname: "Dunford",
    gender: "Male",
    dob: "2/21/1998",
    emailid: "mdunford12@deliciousdays.com",
    phoneno: "2742950336",
    address: "0 Becker Junction",
    tokenid: 37,
    companyid: 12,
    createdby: "Merry",
    createddate: "11/8/2021",
  },
  {
    firstname: "Hogan",
    middlename: "Hugues",
    lastname: "Murrhaupt",
    gender: "Male",
    dob: "10/5/2000",
    emailid: "kmurrhaupt13@people.com.cn",
    phoneno: "5925205873",
    address: "55 Tennessee Court",
    tokenid: 29,
    companyid: 10,
    createdby: "Kerry",
    createddate: "1/24/2022",
  },
  {
    firstname: "Janot",
    middlename: "Missy",
    lastname: "Hamner",
    gender: "Female",
    dob: "9/27/1998",
    emailid: "phamner14@tumblr.com",
    phoneno: "1412862722",
    address: "6626 Comanche Trail",
    tokenid: 92,
    companyid: 60,
    createdby: "Philly",
    createddate: "6/23/2021",
  },
  {
    firstname: "Alley",
    middlename: "Bruno",
    lastname: "Inett",
    gender: "Male",
    dob: "3/17/2001",
    emailid: "ninett15@cafepress.com",
    phoneno: "3478145366",
    address: "6212 Rutledge Hill",
    tokenid: 36,
    companyid: 62,
    createdby: "Nichole",
    createddate: "12/3/2020",
  },
  {
    firstname: "Rutherford",
    middlename: "Ermanno",
    lastname: "Chadbourn",
    gender: "Male",
    dob: "1/2/1999",
    emailid: "gchadbourn16@oracle.com",
    phoneno: "6043876578",
    address: "05246 Crest Line Circle",
    tokenid: 87,
    companyid: 99,
    createdby: "Goraud",
    createddate: "9/27/2021",
  },
  {
    firstname: "Jobie",
    middlename: "Adelaide",
    lastname: "McCleod",
    gender: "Female",
    dob: "7/21/1999",
    emailid: "emccleod17@home.pl",
    phoneno: "7942693516",
    address: "805 Victoria Trail",
    tokenid: 98,
    companyid: 16,
    createdby: "Elene",
    createddate: "12/17/2021",
  },
  {
    firstname: "Leela",
    middlename: "Tana",
    lastname: "Skinner",
    gender: "Female",
    dob: "10/19/1997",
    emailid: "sskinner18@bizjournals.com",
    phoneno: "9616349648",
    address: "4628 Darwin Road",
    tokenid: 29,
    companyid: 16,
    createdby: "Sorcha",
    createddate: "11/12/2021",
  },
  {
    firstname: "Adriena",
    middlename: "Zoe",
    lastname: "Shemwell",
    gender: "Female",
    dob: "1/29/1998",
    emailid: "sshemwell19@altervista.org",
    phoneno: "8965686252",
    address: "3529 Debra Terrace",
    tokenid: 78,
    companyid: 95,
    createdby: "Sarena",
    createddate: "8/21/2021",
  },
  {
    firstname: "Roth",
    middlename: "Bealle",
    lastname: "Hansberry",
    gender: "Male",
    dob: "2/8/1999",
    emailid: "hhansberry1a@diigo.com",
    phoneno: "7209746248",
    address: "2 Waxwing Street",
    tokenid: 97,
    companyid: 7,
    createdby: "Haily",
    createddate: "3/11/2022",
  },
  {
    firstname: "Lira",
    middlename: "Natka",
    lastname: "Sesons",
    gender: "Female",
    dob: "3/19/2000",
    emailid: "rsesons1b@dailymail.co.uk",
    phoneno: "7743543595",
    address: "0 Burning Wood Hill",
    tokenid: 12,
    companyid: 72,
    createdby: "Rebekkah",
    createddate: "12/24/2021",
  },
  {
    firstname: "Melisandra",
    middlename: "Rosa",
    lastname: "Sepey",
    gender: "Female",
    dob: "3/13/1999",
    emailid: "bsepey1c@google.co.uk",
    phoneno: "8879062368",
    address: "7341 Mcbride Point",
    tokenid: 65,
    companyid: 57,
    createdby: "Bee",
    createddate: "11/20/2021",
  },
  {
    firstname: "Kalie",
    middlename: "Beulah",
    lastname: "Ordelt",
    gender: "Female",
    dob: "7/31/1999",
    emailid: "kordelt1d@odnoklassniki.ru",
    phoneno: "1943395658",
    address: "73 Manley Lane",
    tokenid: 50,
    companyid: 80,
    createdby: "Kizzie",
    createddate: "7/27/2021",
  },
  {
    firstname: "Anestassia",
    middlename: "Toni",
    lastname: "Cattle",
    gender: "Female",
    dob: "8/22/1997",
    emailid: "bcattle1e@springer.com",
    phoneno: "1692183301",
    address: "9795 Amoth Drive",
    tokenid: 30,
    companyid: 9,
    createdby: "Bobbee",
    createddate: "1/9/2021",
  },
  {
    firstname: "Tatiana",
    middlename: "Keeley",
    lastname: "Quaif",
    gender: "Female",
    dob: "6/11/2001",
    emailid: "lquaif1f@51.la",
    phoneno: "4863533682",
    address: "06854 Ryan Circle",
    tokenid: 45,
    companyid: 20,
    createdby: "Lettie",
    createddate: "12/14/2021",
  },
  {
    firstname: "Armin",
    middlename: "Ginger",
    lastname: "Calder",
    gender: "Male",
    dob: "11/21/1997",
    emailid: "pcalder1g@fastcompany.com",
    phoneno: "4171305028",
    address: "3587 Granby Pass",
    tokenid: 30,
    companyid: 67,
    createdby: "Preston",
    createddate: "12/5/2021",
  },
  {
    firstname: "Gizela",
    middlename: "Cloris",
    lastname: "Bilbrey",
    gender: "Female",
    dob: "12/3/1997",
    emailid: "mbilbrey1h@squarespace.com",
    phoneno: "5741576613",
    address: "2 Duke Alley",
    tokenid: 89,
    companyid: 32,
    createdby: "Mariette",
    createddate: "5/24/2021",
  },
  {
    firstname: "Rachele",
    middlename: "Dominica",
    lastname: "Wise",
    gender: "Female",
    dob: "8/18/1998",
    emailid: "bwise1i@about.com",
    phoneno: "1822442067",
    address: "36766 Sloan Park",
    tokenid: 57,
    companyid: 70,
    createdby: "Bonnie",
    createddate: "10/1/2021",
  },
  {
    firstname: "Dina",
    middlename: "Natassia",
    lastname: "Karlicek",
    gender: "Female",
    dob: "6/18/2001",
    emailid: "lkarlicek1j@myspace.com",
    phoneno: "3267523959",
    address: "28 Eastwood Street",
    tokenid: 24,
    companyid: 83,
    createdby: "Leeann",
    createddate: "8/13/2020",
  },
  {
    firstname: "Garwood",
    middlename: "Agosto",
    lastname: "Blas",
    gender: "Male",
    dob: "4/15/1999",
    emailid: "yblas1k@wsj.com",
    phoneno: "8609331529",
    address: "6 Nelson Center",
    tokenid: 30,
    companyid: 12,
    createdby: "Yurik",
    createddate: "5/23/2022",
  },
  {
    firstname: "Wynnie",
    middlename: "Riannon",
    lastname: "Searson",
    gender: "Female",
    dob: "4/9/2001",
    emailid: "ksearson1l@mtv.com",
    phoneno: "9897454790",
    address: "19017 Sycamore Pass",
    tokenid: 17,
    companyid: 70,
    createdby: "Karlee",
    createddate: "7/31/2021",
  },
  {
    firstname: "Elsy",
    middlename: "Cyndi",
    lastname: "Blight",
    gender: "Female",
    dob: "10/9/2000",
    emailid: "jblight1m@squarespace.com",
    phoneno: "6702141654",
    address: "236 Dottie Pass",
    tokenid: 43,
    companyid: 94,
    createdby: "Jorry",
    createddate: "7/27/2020",
  },
  {
    firstname: "Read",
    middlename: "Araldo",
    lastname: "Schoffler",
    gender: "Male",
    dob: "12/22/1998",
    emailid: "kschoffler1n@whitehouse.gov",
    phoneno: "4025337066",
    address: "6219 Maple Park",
    tokenid: 36,
    companyid: 23,
    createdby: "Kellby",
    createddate: "7/17/2020",
  },
  {
    firstname: "Waylin",
    middlename: "Jamil",
    lastname: "Stobbart",
    gender: "Male",
    dob: "12/6/1999",
    emailid: "rstobbart1o@creativecommons.org",
    phoneno: "4036563126",
    address: "4494 Lillian Trail",
    tokenid: 34,
    companyid: 26,
    createdby: "Randy",
    createddate: "5/17/2022",
  },
  {
    firstname: "Wat",
    middlename: "Vincents",
    lastname: "Bambra",
    gender: "Male",
    dob: "6/22/1999",
    emailid: "rbambra1p@blogger.com",
    phoneno: "4533073707",
    address: "71 Sundown Trail",
    tokenid: 82,
    companyid: 72,
    createdby: "Reagan",
    createddate: "2/4/2021",
  },
  {
    firstname: "Leah",
    middlename: "Denni",
    lastname: "Seys",
    gender: "Female",
    dob: "10/18/1997",
    emailid: "kseys1q@arizona.edu",
    phoneno: "6156703265",
    address: "79 Aberg Park",
    tokenid: 36,
    companyid: 44,
    createdby: "Kate",
    createddate: "11/7/2020",
  },
  {
    firstname: "Bria",
    middlename: "Peggi",
    lastname: "Gun",
    gender: "Female",
    dob: "5/21/1999",
    emailid: "cgun1r@example.com",
    phoneno: "4312850766",
    address: "1 Bayside Pass",
    tokenid: 80,
    companyid: 17,
    createdby: "Concettina",
    createddate: "1/22/2021",
  },
  {
    firstname: "Correna",
    middlename: "Ada",
    lastname: "Rylatt",
    gender: "Female",
    dob: "3/10/2000",
    emailid: "grylatt1s@123-reg.co.uk",
    phoneno: "9329910467",
    address: "2707 Sundown Plaza",
    tokenid: 17,
    companyid: 12,
    createdby: "Gilbertina",
    createddate: "12/20/2020",
  },
  {
    firstname: "Brodie",
    middlename: "Barrie",
    lastname: "Edgeller",
    gender: "Male",
    dob: "10/21/1998",
    emailid: "jedgeller1t@zdnet.com",
    phoneno: "6691603402",
    address: "0 Tennyson Plaza",
    tokenid: 43,
    companyid: 82,
    createdby: "Jamal",
    createddate: "2/12/2022",
  },
  {
    firstname: "Augustus",
    middlename: "Shurwood",
    lastname: "Chantrell",
    gender: "Male",
    dob: "5/7/2001",
    emailid: "achantrell1u@simplemachines.org",
    phoneno: "8185380942",
    address: "71 Fair Oaks Park",
    tokenid: 17,
    companyid: 99,
    createdby: "Abbott",
    createddate: "7/7/2021",
  },
  {
    firstname: "Rocky",
    middlename: "Isidor",
    lastname: "Sarchwell",
    gender: "Male",
    dob: "5/14/1998",
    emailid: "isarchwell1v@dyndns.org",
    phoneno: "7167684963",
    address: "410 Huxley Drive",
    tokenid: 18,
    companyid: 75,
    createdby: "Iggy",
    createddate: "8/20/2021",
  },
  {
    firstname: "Shelley",
    middlename: "Cash",
    lastname: "Eadmeades",
    gender: "Male",
    dob: "8/4/2000",
    emailid: "weadmeades1w@dailymail.co.uk",
    phoneno: "4366861276",
    address: "234 Florence Trail",
    tokenid: 76,
    companyid: 78,
    createdby: "Wally",
    createddate: "6/6/2021",
  },
  {
    firstname: "Emmy",
    middlename: "Enrika",
    lastname: "Howkins",
    gender: "Female",
    dob: "1/16/2000",
    emailid: "jhowkins1x@sphinn.com",
    phoneno: "5656603977",
    address: "5241 Kim Circle",
    tokenid: 57,
    companyid: 25,
    createdby: "Janis",
    createddate: "4/27/2022",
  },
  {
    firstname: "Dru",
    middlename: "Chelsea",
    lastname: "Bernlin",
    gender: "Female",
    dob: "10/21/1997",
    emailid: "sbernlin1y@e-recht24.de",
    phoneno: "6427623652",
    address: "4 Sachs Trail",
    tokenid: 96,
    companyid: 62,
    createdby: "Steffie",
    createddate: "3/16/2022",
  },
  {
    firstname: "Jock",
    middlename: "Jere",
    lastname: "Aikin",
    gender: "Male",
    dob: "1/4/1999",
    emailid: "haikin1z@twitpic.com",
    phoneno: "7743430635",
    address: "226 Mendota Drive",
    tokenid: 8,
    companyid: 32,
    createdby: "Heywood",
    createddate: "5/23/2021",
  },
  {
    firstname: "Reggie",
    middlename: "Patty",
    lastname: "Jacop",
    gender: "Female",
    dob: "8/25/1997",
    emailid: "kjacop20@icq.com",
    phoneno: "8695168026",
    address: "81 Oakridge Park",
    tokenid: 49,
    companyid: 15,
    createdby: "Konstanze",
    createddate: "11/15/2020",
  },
  {
    firstname: "Winne",
    middlename: "Enrika",
    lastname: "Challens",
    gender: "Female",
    dob: "4/3/1999",
    emailid: "schallens21@so-net.ne.jp",
    phoneno: "8329650118",
    address: "11269 Hermina Road",
    tokenid: 70,
    companyid: 1,
    createdby: "Sindee",
    createddate: "4/7/2022",
  },
  {
    firstname: "Rice",
    middlename: "Roscoe",
    lastname: "Guerrazzi",
    gender: "Male",
    dob: "5/18/2000",
    emailid: "rguerrazzi22@usda.gov",
    phoneno: "1975947523",
    address: "14 Sullivan Pass",
    tokenid: 97,
    companyid: 71,
    createdby: "Renado",
    createddate: "12/20/2021",
  },
  {
    firstname: "Hurleigh",
    middlename: "Karney",
    lastname: "Rough",
    gender: "Male",
    dob: "7/28/2000",
    emailid: "drough23@hud.gov",
    phoneno: "7116946166",
    address: "0983 Del Mar Hill",
    tokenid: 6,
    companyid: 78,
    createdby: "Darius",
    createddate: "4/15/2021",
  },
  {
    firstname: "Byrom",
    middlename: "Parnell",
    lastname: "Skittreal",
    gender: "Male",
    dob: "8/26/2000",
    emailid: "yskittreal24@friendfeed.com",
    phoneno: "4697670756",
    address: "8644 Corry Drive",
    tokenid: 50,
    companyid: 9,
    createdby: "York",
    createddate: "3/17/2021",
  },
  {
    firstname: "Bentley",
    middlename: "Mayer",
    lastname: "Fathers",
    gender: "Male",
    dob: "11/10/1998",
    emailid: "ufathers25@mozilla.org",
    phoneno: "9376582868",
    address: "404 Corben Place",
    tokenid: 11,
    companyid: 97,
    createdby: "Uriel",
    createddate: "9/25/2020",
  },
  {
    firstname: "Cort",
    middlename: "Ulises",
    lastname: "Arnald",
    gender: "Male",
    dob: "6/16/1999",
    emailid: "warnald26@census.gov",
    phoneno: "4488073945",
    address: "5 Mariners Cove Street",
    tokenid: 25,
    companyid: 25,
    createdby: "Wheeler",
    createddate: "11/13/2021",
  },
  {
    firstname: "Zea",
    middlename: "Ada",
    lastname: "Hendin",
    gender: "Female",
    dob: "9/23/1998",
    emailid: "ahendin27@answers.com",
    phoneno: "5124048377",
    address: "2513 Debs Trail",
    tokenid: 2,
    companyid: 33,
    createdby: "Andrea",
    createddate: "1/5/2021",
  },
  {
    firstname: "L;urette",
    middlename: "Kyrstin",
    lastname: "Jochanany",
    gender: "Female",
    dob: "7/2/2000",
    emailid: "kjochanany28@google.it",
    phoneno: "5776863127",
    address: "83301 Springview Park",
    tokenid: 48,
    companyid: 79,
    createdby: "Kerry",
    createddate: "12/18/2020",
  },
  {
    firstname: "Zeke",
    middlename: "Petey",
    lastname: "Lepere",
    gender: "Male",
    dob: "3/23/1999",
    emailid: "rlepere29@cmu.edu",
    phoneno: "7938421008",
    address: "895 Ridgeview Center",
    tokenid: 38,
    companyid: 65,
    createdby: "Ricky",
    createddate: "3/8/2021",
  },
  {
    firstname: "Blane",
    middlename: "Rinaldo",
    lastname: "MacCambridge",
    gender: "Male",
    dob: "6/2/2001",
    emailid: "amaccambridge2a@noaa.gov",
    phoneno: "9954507801",
    address: "3 Reinke Street",
    tokenid: 89,
    companyid: 50,
    createdby: "Abie",
    createddate: "8/10/2020",
  },
  {
    firstname: "Leyla",
    middlename: "Wanids",
    lastname: "Jollie",
    gender: "Female",
    dob: "8/9/1997",
    emailid: "ljollie2b@purevolume.com",
    phoneno: "1474398112",
    address: "3569 Nobel Street",
    tokenid: 2,
    companyid: 42,
    createdby: "Lorna",
    createddate: "2/13/2021",
  },
  {
    firstname: "Gaston",
    middlename: "Claudian",
    lastname: "Maruszewski",
    gender: "Male",
    dob: "8/9/2000",
    emailid: "tmaruszewski2c@nih.gov",
    phoneno: "2427530511",
    address: "70264 Di Loreto Road",
    tokenid: 71,
    companyid: 16,
    createdby: "Trefor",
    createddate: "3/22/2021",
  },
  {
    firstname: "Garvin",
    middlename: "Townie",
    lastname: "Bennedick",
    gender: "Male",
    dob: "8/14/1998",
    emailid: "kbennedick2d@businessinsider.com",
    phoneno: "3253753867",
    address: "7 Norway Maple Road",
    tokenid: 61,
    companyid: 39,
    createdby: "Kiley",
    createddate: "10/29/2020",
  },
  {
    firstname: "Artus",
    middlename: "Humbert",
    lastname: "Winks",
    gender: "Male",
    dob: "12/24/1998",
    emailid: "mwinks2e@aol.com",
    phoneno: "5601170210",
    address: "71 Commercial Trail",
    tokenid: 91,
    companyid: 29,
    createdby: "Montague",
    createddate: "12/13/2021",
  },
  {
    firstname: "Yankee",
    middlename: "Morten",
    lastname: "Cawson",
    gender: "Male",
    dob: "8/18/1998",
    emailid: "bcawson2f@jiathis.com",
    phoneno: "2763457575",
    address: "601 Merry Plaza",
    tokenid: 22,
    companyid: 58,
    createdby: "Ban",
    createddate: "1/6/2022",
  },
  {
    firstname: "Elena",
    middlename: "Carena",
    lastname: "Matkin",
    gender: "Female",
    dob: "6/8/2001",
    emailid: "mmatkin2g@ca.gov",
    phoneno: "5534785586",
    address: "6 Marcy Trail",
    tokenid: 28,
    companyid: 25,
    createdby: "Malina",
    createddate: "10/15/2020",
  },
  {
    firstname: "Barbe",
    middlename: "Serena",
    lastname: "Swaysland",
    gender: "Female",
    dob: "7/21/1997",
    emailid: "lswaysland2h@woothemes.com",
    phoneno: "8554795304",
    address: "33726 Tennessee Crossing",
    tokenid: 64,
    companyid: 53,
    createdby: "Layne",
    createddate: "1/13/2021",
  },
  {
    firstname: "Margarita",
    middlename: "Rebecka",
    lastname: "Janeway",
    gender: "Female",
    dob: "8/14/1999",
    emailid: "ijaneway2i@yandex.ru",
    phoneno: "8158681102",
    address: "275 Linden Lane",
    tokenid: 96,
    companyid: 13,
    createdby: "Idalina",
    createddate: "7/29/2021",
  },
  {
    firstname: "Tera",
    middlename: "Tori",
    lastname: "Whiteway",
    gender: "Female",
    dob: "7/23/1999",
    emailid: "awhiteway2j@vimeo.com",
    phoneno: "1891435524",
    address: "2 Eagle Crest Drive",
    tokenid: 93,
    companyid: 41,
    createdby: "Ariana",
    createddate: "2/26/2022",
  },
  {
    firstname: "Whitaker",
    middlename: "Kendricks",
    lastname: "Allright",
    gender: "Male",
    dob: "10/23/1998",
    emailid: "gallright2k@sogou.com",
    phoneno: "2283733031",
    address: "08383 Arkansas Hill",
    tokenid: 8,
    companyid: 5,
    createdby: "Gifford",
    createddate: "12/25/2020",
  },
  {
    firstname: "Emanuel",
    middlename: "Ravi",
    lastname: "Gannaway",
    gender: "Male",
    dob: "3/22/2000",
    emailid: "cgannaway2l@1und1.de",
    phoneno: "2928111507",
    address: "8443 Nevada Junction",
    tokenid: 5,
    companyid: 71,
    createdby: "Ced",
    createddate: "3/3/2021",
  },
  {
    firstname: "Wash",
    middlename: "Buckie",
    lastname: "Richardon",
    gender: "Male",
    dob: "3/18/2001",
    emailid: "nrichardon2m@state.tx.us",
    phoneno: "9621514270",
    address: "86621 Valley Edge Parkway",
    tokenid: 48,
    companyid: 2,
    createdby: "Neal",
    createddate: "1/9/2022",
  },
  {
    firstname: "Bartlett",
    middlename: "Wolfy",
    lastname: "Troyes",
    gender: "Male",
    dob: "2/24/2001",
    emailid: "ptroyes2n@globo.com",
    phoneno: "2556411260",
    address: "846 7th Park",
    tokenid: 29,
    companyid: 84,
    createdby: "Pinchas",
    createddate: "7/10/2021",
  },
  {
    firstname: "Imojean",
    middlename: "Gilly",
    lastname: "von Hagt",
    gender: "Female",
    dob: "10/24/1997",
    emailid: "cvonhagt2o@mediafire.com",
    phoneno: "9823330967",
    address: "047 Coleman Crossing",
    tokenid: 95,
    companyid: 49,
    createdby: "Cassaundra",
    createddate: "3/20/2021",
  },
  {
    firstname: "Jeannie",
    middlename: "Francine",
    lastname: "Colly",
    gender: "Female",
    dob: "5/1/2001",
    emailid: "mcolly2p@unesco.org",
    phoneno: "1269151655",
    address: "82293 Becker Way",
    tokenid: 39,
    companyid: 33,
    createdby: "Mellicent",
    createddate: "10/17/2021",
  },
  {
    firstname: "Alisun",
    middlename: "Enid",
    lastname: "Eixenberger",
    gender: "Female",
    dob: "1/1/1998",
    emailid: "meixenberger2q@51.la",
    phoneno: "3427151287",
    address: "6836 Blaine Road",
    tokenid: 87,
    companyid: 35,
    createdby: "Maryjane",
    createddate: "12/1/2020",
  },
  {
    firstname: "Benji",
    middlename: "Theo",
    lastname: "Hadleigh",
    gender: "Male",
    dob: "9/21/2000",
    emailid: "shadleigh2r@timesonline.co.uk",
    phoneno: "7543263858",
    address: "49 Artisan Lane",
    tokenid: 48,
    companyid: 26,
    createdby: "Schuyler",
    createddate: "4/14/2022",
  },
];

const db = require("../server/config/database");
let obj;
for (obj of Data) {
  const keys = Object.keys(obj);
  const values = Object.values(obj);
  const sql = `insert into individual (${keys}) values (${values.map(
    (item) => `'${item}'`
  )})`;
  // console.log(sql);
  db.query(sql);
}
