name: pull-request

on:
  pull_request:
    branches: [main]
  
  jobs:
    build:
    
      strategy:
        matrix:
          node_version: ['14', '16']
          os: [ubuntu-latest, windows-latest, macOS-latest]
          
      runs-on: ${{ matrix.os}}
      steps:
        - name: Check out source code
          uses: actions/checkout@v2
          
        - name: setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node_version }}
          
        - name: Install dependencies
          run: npm install
          
        - name: 
